version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      root-dependencies:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /dashboard
    schedule:
      interval: weekly
    groups:
      dashboard-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
