// AUTO-GENERATED by scripts/gen-routes.mjs — do not edit.
export const ROUTE_LOADERS = {
  "api/auth/login/route.js": () => import("./api/auth/login/route.js"),
  "api/auth/logout/route.js": () => import("./api/auth/logout/route.js"),
  "api/auth/oidc/callback/route.js": () => import("./api/auth/oidc/callback/route.js"),
  "api/auth/oidc/start/route.js": () => import("./api/auth/oidc/start/route.js"),
  "api/auth/oidc/test/route.js": () => import("./api/auth/oidc/test/route.js"),
  "api/auth/reset-password/route.js": () => import("./api/auth/reset-password/route.js"),
  "api/auth/status/route.js": () => import("./api/auth/status/route.js"),
  "api/auth/verify-password/route.js": () => import("./api/auth/verify-password/route.js"),
  "api/chat/tools/curl/route.js": () => import("./api/chat/tools/curl/route.js"),
  "api/chat/tools/router/route.js": () => import("./api/chat/tools/router/route.js"),
  "api/chat/tools/search/route.js": () => import("./api/chat/tools/search/route.js"),
  "api/chat/tools/shell/route.js": () => import("./api/chat/tools/shell/route.js"),
  "api/cli-tools/all-statuses/route.js": () => import("./api/cli-tools/all-statuses/route.js"),
  "api/cli-tools/claude-settings/route.js": () => import("./api/cli-tools/claude-settings/route.js"),
  "api/cli-tools/codex-settings/route.js": () => import("./api/cli-tools/codex-settings/route.js"),
  "api/cli-tools/cowork-mcp-registry/route.js": () => import("./api/cli-tools/cowork-mcp-registry/route.js"),
  "api/cli-tools/cowork-mcp-tools/route.js": () => import("./api/cli-tools/cowork-mcp-tools/route.js"),
  "api/cli-tools/cowork-settings/route.js": () => import("./api/cli-tools/cowork-settings/route.js"),
  "api/cli-tools/grok-build-settings/route.js": () => import("./api/cli-tools/grok-build-settings/route.js"),
  "api/cli-tools/hermes-settings/route.js": () => import("./api/cli-tools/hermes-settings/route.js"),
  "api/cli-tools/kilo-settings/route.js": () => import("./api/cli-tools/kilo-settings/route.js"),
  "api/cli-tools/model-mappings/route.js": () => import("./api/cli-tools/model-mappings/route.js"),
  "api/cli-tools/omp-settings/route.js": () => import("./api/cli-tools/omp-settings/route.js"),
  "api/cli-tools/opencode-settings/route.js": () => import("./api/cli-tools/opencode-settings/route.js"),
  "api/combos/[id]/route.js": () => import("./api/combos/[id]/route.js"),
  "api/combos/route.js": () => import("./api/combos/route.js"),
  "api/health/live/route.js": () => import("./api/health/live/route.js"),
  "api/health/ready/route.js": () => import("./api/health/ready/route.js"),
  "api/health/route.js": () => import("./api/health/route.js"),
  "api/inflight/stream/route.js": () => import("./api/inflight/stream/route.js"),
  "api/init/route.js": () => import("./api/init/route.js"),
  "api/keys/[id]/route.js": () => import("./api/keys/[id]/route.js"),
  "api/keys/route.js": () => import("./api/keys/route.js"),
  "api/logs/route.js": () => import("./api/logs/route.js"),
  "api/mcp/[plugin]/message/route.js": () => import("./api/mcp/[plugin]/message/route.js"),
  "api/mcp/[plugin]/sse/route.js": () => import("./api/mcp/[plugin]/sse/route.js"),
  "api/models/availability/route.js": () => import("./api/models/availability/route.js"),
  "api/models/custom/route.js": () => import("./api/models/custom/route.js"),
  "api/models/disabled/route.js": () => import("./api/models/disabled/route.js"),
  "api/models/route.js": () => import("./api/models/route.js"),
  "api/models/test/route.js": () => import("./api/models/test/route.js"),
  "api/oauth/[provider]/[action]/route.js": () => import("./api/oauth/[provider]/[action]/route.js"),
  "api/oauth/codex/bulk-import/route.js": () => import("./api/oauth/codex/bulk-import/route.js"),
  "api/oauth/codex/import-token/route.js": () => import("./api/oauth/codex/import-token/route.js"),
  "api/oauth/cursor/auto-import/route.js": () => import("./api/oauth/cursor/auto-import/route.js"),
  "api/oauth/cursor/import/route.js": () => import("./api/oauth/cursor/import/route.js"),
  "api/oauth/kiro/api-key/route.js": () => import("./api/oauth/kiro/api-key/route.js"),
  "api/oauth/kiro/auto-import/route.js": () => import("./api/oauth/kiro/auto-import/route.js"),
  "api/oauth/kiro/import-cli-proxy/route.js": () => import("./api/oauth/kiro/import-cli-proxy/route.js"),
  "api/oauth/kiro/import/route.js": () => import("./api/oauth/kiro/import/route.js"),
  "api/oauth/kiro/social-authorize/route.js": () => import("./api/oauth/kiro/social-authorize/route.js"),
  "api/oauth/kiro/social-exchange/route.js": () => import("./api/oauth/kiro/social-exchange/route.js"),
  "api/pricing/route.js": () => import("./api/pricing/route.js"),
  "api/provider-nodes/[id]/route.js": () => import("./api/provider-nodes/[id]/route.js"),
  "api/provider-nodes/route.js": () => import("./api/provider-nodes/route.js"),
  "api/provider-nodes/validate/route.js": () => import("./api/provider-nodes/validate/route.js"),
  "api/providers/[id]/models/route.js": () => import("./api/providers/[id]/models/route.js"),
  "api/providers/[id]/route.js": () => import("./api/providers/[id]/route.js"),
  "api/providers/[id]/test-models/route.js": () => import("./api/providers/[id]/test-models/route.js"),
  "api/providers/[id]/test/route.js": () => import("./api/providers/[id]/test/route.js"),
  "api/providers/catalog/route.js": () => import("./api/providers/catalog/route.js"),
  "api/providers/client/route.js": () => import("./api/providers/client/route.js"),
  "api/providers/counts/route.js": () => import("./api/providers/counts/route.js"),
  "api/providers/kilo/free-models/route.js": () => import("./api/providers/kilo/free-models/route.js"),
  "api/providers/route.js": () => import("./api/providers/route.js"),
  "api/providers/suggested-models/route.js": () => import("./api/providers/suggested-models/route.js"),
  "api/providers/test-batch/route.js": () => import("./api/providers/test-batch/route.js"),
  "api/providers/validate/route.js": () => import("./api/providers/validate/route.js"),
  "api/proxy-pools/[id]/route.js": () => import("./api/proxy-pools/[id]/route.js"),
  "api/proxy-pools/[id]/test/route.js": () => import("./api/proxy-pools/[id]/test/route.js"),
  "api/proxy-pools/cloudflare-deploy/route.js": () => import("./api/proxy-pools/cloudflare-deploy/route.js"),
  "api/proxy-pools/route.js": () => import("./api/proxy-pools/route.js"),
  "api/proxy-pools/vercel-deploy/route.js": () => import("./api/proxy-pools/vercel-deploy/route.js"),
  "api/settings/currency/route.js": () => import("./api/settings/currency/route.js"),
  "api/settings/database/path/route.js": () => import("./api/settings/database/path/route.js"),
  "api/settings/database/route.js": () => import("./api/settings/database/route.js"),
  "api/settings/migrate-9router/route.js": () => import("./api/settings/migrate-9router/route.js"),
  "api/settings/require-login/route.js": () => import("./api/settings/require-login/route.js"),
  "api/settings/route.js": () => import("./api/settings/route.js"),
  "api/shutdown/route.js": () => import("./api/shutdown/route.js"),
  "api/tags/route.js": () => import("./api/tags/route.js"),
  "api/translator/console-logs/route.js": () => import("./api/translator/console-logs/route.js"),
  "api/translator/console-logs/stream/route.js": () => import("./api/translator/console-logs/stream/route.js"),
  "api/tunnel/disable/route.js": () => import("./api/tunnel/disable/route.js"),
  "api/tunnel/enable/route.js": () => import("./api/tunnel/enable/route.js"),
  "api/tunnel/status/route.js": () => import("./api/tunnel/status/route.js"),
  "api/update/route.js": () => import("./api/update/route.js"),
  "api/usage/[connectionId]/codex-reset-credits/route.js": () => import("./api/usage/[connectionId]/codex-reset-credits/route.js"),
  "api/usage/[connectionId]/route.js": () => import("./api/usage/[connectionId]/route.js"),
  "api/usage/chart/route.js": () => import("./api/usage/chart/route.js"),
  "api/usage/history/route.js": () => import("./api/usage/history/route.js"),
  "api/usage/logs/route.js": () => import("./api/usage/logs/route.js"),
  "api/usage/providers/route.js": () => import("./api/usage/providers/route.js"),
  "api/usage/request-details/route.js": () => import("./api/usage/request-details/route.js"),
  "api/usage/request-logs/route.js": () => import("./api/usage/request-logs/route.js"),
  "api/usage/stats/route.js": () => import("./api/usage/stats/route.js"),
  "api/usage/stream/route.js": () => import("./api/usage/stream/route.js"),
  "api/v1/api/chat/route.js": () => import("./api/v1/api/chat/route.js"),
  "api/v1/chat/completions/route.js": () => import("./api/v1/chat/completions/route.js"),
  "api/v1/images/edits/route.js": () => import("./api/v1/images/edits/route.js"),
  "api/v1/images/generations/route.js": () => import("./api/v1/images/generations/route.js"),
  "api/v1/messages/count_tokens/route.js": () => import("./api/v1/messages/count_tokens/route.js"),
  "api/v1/messages/route.js": () => import("./api/v1/messages/route.js"),
  "api/v1/models/route.js": () => import("./api/v1/models/route.js"),
  "api/v1/responses/compact/route.js": () => import("./api/v1/responses/compact/route.js"),
  "api/v1/responses/route.js": () => import("./api/v1/responses/route.js"),
  "api/v1/route.js": () => import("./api/v1/route.js"),
  "api/version/route.js": () => import("./api/version/route.js"),
};

export const ROUTE_TABLE = [
  {
    "method": "DELETE",
    "pathPattern": "/api/cli-tools/claude-settings",
    "file": "api/cli-tools/claude-settings/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/cli-tools/codex-settings",
    "file": "api/cli-tools/codex-settings/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/cli-tools/cowork-settings",
    "file": "api/cli-tools/cowork-settings/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/cli-tools/grok-build-settings",
    "file": "api/cli-tools/grok-build-settings/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/cli-tools/hermes-settings",
    "file": "api/cli-tools/hermes-settings/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/cli-tools/kilo-settings",
    "file": "api/cli-tools/kilo-settings/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/cli-tools/model-mappings",
    "file": "api/cli-tools/model-mappings/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/cli-tools/omp-settings",
    "file": "api/cli-tools/omp-settings/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/cli-tools/opencode-settings",
    "file": "api/cli-tools/opencode-settings/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/combos/:id",
    "file": "api/combos/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/keys/:id",
    "file": "api/keys/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/models/custom",
    "file": "api/models/custom/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/models/disabled",
    "file": "api/models/disabled/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/pricing",
    "file": "api/pricing/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/provider-nodes/:id",
    "file": "api/provider-nodes/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/providers/:id",
    "file": "api/providers/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/proxy-pools/:id",
    "file": "api/proxy-pools/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/translator/console-logs",
    "file": "api/translator/console-logs/route.js",
    "params": []
  },
  {
    "method": "DELETE",
    "pathPattern": "/api/usage/history",
    "file": "api/usage/history/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/auth/oidc/callback",
    "file": "api/auth/oidc/callback/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/auth/oidc/start",
    "file": "api/auth/oidc/start/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/auth/status",
    "file": "api/auth/status/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/cli-tools/all-statuses",
    "file": "api/cli-tools/all-statuses/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/cli-tools/claude-settings",
    "file": "api/cli-tools/claude-settings/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/cli-tools/codex-settings",
    "file": "api/cli-tools/codex-settings/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/cli-tools/cowork-mcp-registry",
    "file": "api/cli-tools/cowork-mcp-registry/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/cli-tools/cowork-settings",
    "file": "api/cli-tools/cowork-settings/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/cli-tools/grok-build-settings",
    "file": "api/cli-tools/grok-build-settings/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/cli-tools/hermes-settings",
    "file": "api/cli-tools/hermes-settings/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/cli-tools/kilo-settings",
    "file": "api/cli-tools/kilo-settings/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/cli-tools/model-mappings",
    "file": "api/cli-tools/model-mappings/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/cli-tools/omp-settings",
    "file": "api/cli-tools/omp-settings/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/cli-tools/opencode-settings",
    "file": "api/cli-tools/opencode-settings/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/combos",
    "file": "api/combos/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/combos/:id",
    "file": "api/combos/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "GET",
    "pathPattern": "/api/health",
    "file": "api/health/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/health/live",
    "file": "api/health/live/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/health/ready",
    "file": "api/health/ready/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/inflight/stream",
    "file": "api/inflight/stream/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/init",
    "file": "api/init/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/keys",
    "file": "api/keys/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/keys/:id",
    "file": "api/keys/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "GET",
    "pathPattern": "/api/logs",
    "file": "api/logs/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/mcp/:plugin/sse",
    "file": "api/mcp/[plugin]/sse/route.js",
    "params": [
      "plugin"
    ]
  },
  {
    "method": "GET",
    "pathPattern": "/api/models",
    "file": "api/models/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/models/availability",
    "file": "api/models/availability/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/models/custom",
    "file": "api/models/custom/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/models/disabled",
    "file": "api/models/disabled/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/oauth/cursor/auto-import",
    "file": "api/oauth/cursor/auto-import/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/oauth/cursor/import",
    "file": "api/oauth/cursor/import/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/oauth/kiro/auto-import",
    "file": "api/oauth/kiro/auto-import/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/oauth/kiro/social-authorize",
    "file": "api/oauth/kiro/social-authorize/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/oauth/:provider/:action",
    "file": "api/oauth/[provider]/[action]/route.js",
    "params": [
      "provider",
      "action"
    ]
  },
  {
    "method": "GET",
    "pathPattern": "/api/pricing",
    "file": "api/pricing/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/provider-nodes",
    "file": "api/provider-nodes/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/providers",
    "file": "api/providers/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/providers/catalog",
    "file": "api/providers/catalog/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/providers/client",
    "file": "api/providers/client/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/providers/counts",
    "file": "api/providers/counts/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/providers/kilo/free-models",
    "file": "api/providers/kilo/free-models/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/providers/suggested-models",
    "file": "api/providers/suggested-models/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/providers/:id",
    "file": "api/providers/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "GET",
    "pathPattern": "/api/providers/:id/models",
    "file": "api/providers/[id]/models/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "GET",
    "pathPattern": "/api/proxy-pools",
    "file": "api/proxy-pools/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/proxy-pools/:id",
    "file": "api/proxy-pools/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "GET",
    "pathPattern": "/api/settings",
    "file": "api/settings/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/settings/currency",
    "file": "api/settings/currency/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/settings/database",
    "file": "api/settings/database/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/settings/database/path",
    "file": "api/settings/database/path/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/settings/migrate-9router",
    "file": "api/settings/migrate-9router/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/settings/require-login",
    "file": "api/settings/require-login/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/tags",
    "file": "api/tags/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/translator/console-logs",
    "file": "api/translator/console-logs/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/translator/console-logs/stream",
    "file": "api/translator/console-logs/stream/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/tunnel/status",
    "file": "api/tunnel/status/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/usage/chart",
    "file": "api/usage/chart/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/usage/history",
    "file": "api/usage/history/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/usage/logs",
    "file": "api/usage/logs/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/usage/providers",
    "file": "api/usage/providers/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/usage/request-details",
    "file": "api/usage/request-details/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/usage/request-logs",
    "file": "api/usage/request-logs/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/usage/stats",
    "file": "api/usage/stats/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/usage/stream",
    "file": "api/usage/stream/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/usage/:connectionId",
    "file": "api/usage/[connectionId]/route.js",
    "params": [
      "connectionId"
    ]
  },
  {
    "method": "GET",
    "pathPattern": "/api/usage/:connectionId/codex-reset-credits",
    "file": "api/usage/[connectionId]/codex-reset-credits/route.js",
    "params": [
      "connectionId"
    ]
  },
  {
    "method": "GET",
    "pathPattern": "/api/v1",
    "file": "api/v1/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/v1/models",
    "file": "api/v1/models/route.js",
    "params": []
  },
  {
    "method": "GET",
    "pathPattern": "/api/version",
    "file": "api/version/route.js",
    "params": []
  },
  {
    "method": "OPTIONS",
    "pathPattern": "/api/health",
    "file": "api/health/route.js",
    "params": []
  },
  {
    "method": "OPTIONS",
    "pathPattern": "/api/tags",
    "file": "api/tags/route.js",
    "params": []
  },
  {
    "method": "OPTIONS",
    "pathPattern": "/api/v1",
    "file": "api/v1/route.js",
    "params": []
  },
  {
    "method": "OPTIONS",
    "pathPattern": "/api/v1/api/chat",
    "file": "api/v1/api/chat/route.js",
    "params": []
  },
  {
    "method": "OPTIONS",
    "pathPattern": "/api/v1/chat/completions",
    "file": "api/v1/chat/completions/route.js",
    "params": []
  },
  {
    "method": "OPTIONS",
    "pathPattern": "/api/v1/messages",
    "file": "api/v1/messages/route.js",
    "params": []
  },
  {
    "method": "OPTIONS",
    "pathPattern": "/api/v1/messages/count_tokens",
    "file": "api/v1/messages/count_tokens/route.js",
    "params": []
  },
  {
    "method": "OPTIONS",
    "pathPattern": "/api/v1/models",
    "file": "api/v1/models/route.js",
    "params": []
  },
  {
    "method": "OPTIONS",
    "pathPattern": "/api/v1/responses",
    "file": "api/v1/responses/route.js",
    "params": []
  },
  {
    "method": "OPTIONS",
    "pathPattern": "/api/v1/responses/compact",
    "file": "api/v1/responses/compact/route.js",
    "params": []
  },
  {
    "method": "PATCH",
    "pathPattern": "/api/cli-tools/opencode-settings",
    "file": "api/cli-tools/opencode-settings/route.js",
    "params": []
  },
  {
    "method": "PATCH",
    "pathPattern": "/api/pricing",
    "file": "api/pricing/route.js",
    "params": []
  },
  {
    "method": "PATCH",
    "pathPattern": "/api/settings",
    "file": "api/settings/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/auth/login",
    "file": "api/auth/login/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/auth/logout",
    "file": "api/auth/logout/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/auth/oidc/test",
    "file": "api/auth/oidc/test/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/auth/reset-password",
    "file": "api/auth/reset-password/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/auth/verify-password",
    "file": "api/auth/verify-password/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/chat/tools/curl",
    "file": "api/chat/tools/curl/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/chat/tools/router",
    "file": "api/chat/tools/router/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/chat/tools/search",
    "file": "api/chat/tools/search/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/chat/tools/shell",
    "file": "api/chat/tools/shell/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/cli-tools/claude-settings",
    "file": "api/cli-tools/claude-settings/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/cli-tools/codex-settings",
    "file": "api/cli-tools/codex-settings/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/cli-tools/cowork-mcp-tools",
    "file": "api/cli-tools/cowork-mcp-tools/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/cli-tools/cowork-settings",
    "file": "api/cli-tools/cowork-settings/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/cli-tools/grok-build-settings",
    "file": "api/cli-tools/grok-build-settings/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/cli-tools/hermes-settings",
    "file": "api/cli-tools/hermes-settings/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/cli-tools/kilo-settings",
    "file": "api/cli-tools/kilo-settings/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/cli-tools/omp-settings",
    "file": "api/cli-tools/omp-settings/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/cli-tools/opencode-settings",
    "file": "api/cli-tools/opencode-settings/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/combos",
    "file": "api/combos/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/keys",
    "file": "api/keys/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/mcp/:plugin/message",
    "file": "api/mcp/[plugin]/message/route.js",
    "params": [
      "plugin"
    ]
  },
  {
    "method": "POST",
    "pathPattern": "/api/models/availability",
    "file": "api/models/availability/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/models/custom",
    "file": "api/models/custom/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/models/disabled",
    "file": "api/models/disabled/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/models/test",
    "file": "api/models/test/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/oauth/codex/bulk-import",
    "file": "api/oauth/codex/bulk-import/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/oauth/codex/import-token",
    "file": "api/oauth/codex/import-token/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/oauth/cursor/import",
    "file": "api/oauth/cursor/import/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/oauth/kiro/api-key",
    "file": "api/oauth/kiro/api-key/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/oauth/kiro/import",
    "file": "api/oauth/kiro/import/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/oauth/kiro/import-cli-proxy",
    "file": "api/oauth/kiro/import-cli-proxy/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/oauth/kiro/social-exchange",
    "file": "api/oauth/kiro/social-exchange/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/oauth/:provider/:action",
    "file": "api/oauth/[provider]/[action]/route.js",
    "params": [
      "provider",
      "action"
    ]
  },
  {
    "method": "POST",
    "pathPattern": "/api/provider-nodes",
    "file": "api/provider-nodes/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/provider-nodes/validate",
    "file": "api/provider-nodes/validate/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/providers",
    "file": "api/providers/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/providers/test-batch",
    "file": "api/providers/test-batch/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/providers/validate",
    "file": "api/providers/validate/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/providers/:id/test",
    "file": "api/providers/[id]/test/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "POST",
    "pathPattern": "/api/providers/:id/test-models",
    "file": "api/providers/[id]/test-models/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "POST",
    "pathPattern": "/api/proxy-pools",
    "file": "api/proxy-pools/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/proxy-pools/cloudflare-deploy",
    "file": "api/proxy-pools/cloudflare-deploy/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/proxy-pools/vercel-deploy",
    "file": "api/proxy-pools/vercel-deploy/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/proxy-pools/:id/test",
    "file": "api/proxy-pools/[id]/test/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "POST",
    "pathPattern": "/api/settings/database",
    "file": "api/settings/database/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/settings/migrate-9router",
    "file": "api/settings/migrate-9router/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/shutdown",
    "file": "api/shutdown/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/tunnel/disable",
    "file": "api/tunnel/disable/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/tunnel/enable",
    "file": "api/tunnel/enable/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/update",
    "file": "api/update/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/usage/:connectionId/codex-reset-credits",
    "file": "api/usage/[connectionId]/codex-reset-credits/route.js",
    "params": [
      "connectionId"
    ]
  },
  {
    "method": "POST",
    "pathPattern": "/api/v1/api/chat",
    "file": "api/v1/api/chat/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/v1/chat/completions",
    "file": "api/v1/chat/completions/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/v1/images/edits",
    "file": "api/v1/images/edits/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/v1/images/generations",
    "file": "api/v1/images/generations/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/v1/messages",
    "file": "api/v1/messages/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/v1/messages/count_tokens",
    "file": "api/v1/messages/count_tokens/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/v1/responses",
    "file": "api/v1/responses/route.js",
    "params": []
  },
  {
    "method": "POST",
    "pathPattern": "/api/v1/responses/compact",
    "file": "api/v1/responses/compact/route.js",
    "params": []
  },
  {
    "method": "PUT",
    "pathPattern": "/api/cli-tools/model-mappings",
    "file": "api/cli-tools/model-mappings/route.js",
    "params": []
  },
  {
    "method": "PUT",
    "pathPattern": "/api/combos/:id",
    "file": "api/combos/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "PUT",
    "pathPattern": "/api/keys/:id",
    "file": "api/keys/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "PUT",
    "pathPattern": "/api/provider-nodes/:id",
    "file": "api/provider-nodes/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "PUT",
    "pathPattern": "/api/providers/:id",
    "file": "api/providers/[id]/route.js",
    "params": [
      "id"
    ]
  },
  {
    "method": "PUT",
    "pathPattern": "/api/proxy-pools/:id",
    "file": "api/proxy-pools/[id]/route.js",
    "params": [
      "id"
    ]
  }
];
