blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/envielxyz/SwayRouter/security/advisories/new
    about: Report sensitive security issues privately.
