import { Glob } from "bun";
import path from "node:path";

const ROUTES_ROOT = path.resolve(import.meta.dirname, "../src/routes/api");
const TABLE_OUT = path.resolve(import.meta.dirname, "../src/routes/table.js");

const HTTP_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"];

function toPattern(relDir) {

  const parts = relDir.split("/");
  const patternParts = parts.map((seg) => {
    const m = seg.match(/^\[\.\.\.(\w+)\]$/);
    if (m) return `:${m[1]}*`;
    const p = seg.match(/^\[(\w+)\]$/);
    if (p) return `:${p[1]}`;
    return seg;
  });
  return `/api/${patternParts.join("/")}`;
}

function toParams(relDir) {
  const parts = relDir.split("/");
  const params = [];
  for (const seg of parts) {
    const m = seg.match(/^\[\.\.\.(\w+)\]$/);
    if (m) { params.push(m[1]); continue; }
    const p = seg.match(/^\[(\w+)\]$/);
    if (p) params.push(p[1]);
  }
  return params;
}

const glob = new Glob("**/route.js");
const rows = [];

for (const rel of glob.scanSync({ cwd: ROUTES_ROOT, absolute: true })) {
  const relDir = path.relative(ROUTES_ROOT, path.dirname(rel)).split(path.sep).join("/");
  const pattern = toPattern(relDir);
  const params = toParams(relDir);
  const file = path.relative(path.resolve(import.meta.dirname, "../src/routes"), rel)
    .split(path.sep).join("/");

  let mod;
  try {
    mod = await import(rel);
  } catch (e) {
    console.error(`[gen-routes] FAILED to import ${rel}: ${e.message}`);
    process.exit(1);
  }

  for (const m of HTTP_METHODS) {
    if (typeof mod[m] === "function") {
      rows.push({ method: m, pathPattern: pattern, file, params });
    }
  }
}

const SEG_SPLIT = /\//;

function routeCmp(a, b) {
  if (a.method !== b.method) return a.method.localeCompare(b.method);
  const sa = a.pathPattern.split(SEG_SPLIT);
  const sb = b.pathPattern.split(SEG_SPLIT);
  const len = Math.max(sa.length, sb.length);
  for (let i = 0; i < len; i++) {
    const x = sa[i] ?? "";
    const y = sb[i] ?? "";
    if (x === y) continue;

    if (x === "") return -1;
    if (y === "") return 1;
    const xParam = x.startsWith(":");
    const yParam = y.startsWith(":");
    if (xParam !== yParam) return xParam ? 1 : -1;

    return x.localeCompare(y);
  }
  return a.pathPattern.length - b.pathPattern.length;
}

rows.sort(routeCmp);

const routeFiles = [...new Set(rows.map((row) => row.file))].sort();
const loaders = routeFiles
  .map((file) => `  ${JSON.stringify(file)}: () => import(${JSON.stringify(`./${file}`)}),`)
  .join("\n");
const body = `// AUTO-GENERATED by scripts/gen-routes.mjs — do not edit.
export const ROUTE_LOADERS = {
${loaders}
};

export const ROUTE_TABLE = ${JSON.stringify(rows, null, 2)};
`;
const summary = `${rows.length} route-method rows across ${new Set(rows.map(r => r.file)).size} files`;

if (process.argv.includes("--check")) {
  const current = await Bun.file(TABLE_OUT).text().catch(() => null);
  if (current !== body) {
    console.error(`[gen-routes] ${TABLE_OUT} is stale; run bun scripts/gen-routes.mjs`);
    process.exit(1);
  }
  console.log(`[gen-routes] verified ${TABLE_OUT}: ${summary}`);
} else {
  await Bun.write(TABLE_OUT, body);
  console.log(`[gen-routes] wrote ${TABLE_OUT}: ${summary}`);
}
