import { writeFileSync } from "fs";
import { createDashboardAuthToken } from "../src/lib/auth/dashboardSession.js";

const outFile = process.argv[2] || process.env.TEMP + "/env-smoke/cookies.txt";

const token = await createDashboardAuthToken();
const lines = [
  "# Netscape HTTP Cookie File",
  "# Generated by scripts/mint-cookie.mjs (24h expiry)",
  `localhost\tFALSE\t/\tFALSE\t0\tauth_token\t${token}`,
  "",
];
writeFileSync(outFile, lines.join("\n"));
console.log(`cookie written → ${outFile} (auth_token present)`);
