import type { AvailableProvider } from "@/lib/connections-api";

export const BUILTIN_PROVIDER_CATALOG: AvailableProvider[] = [
  {"id":"alicode","name":"Alibaba","alias":"alicode","category":"apikey","authType":"apikey","color":"#FF6A00","icon":"cloud","textIcon":"ALi"},
  {"id":"alicode-intl","name":"Alibaba Coding","alias":"alicode-intl","category":"apikey","authType":"apikey","color":"#FF6A00","icon":"cloud","textIcon":"ALi"},
  {"id":"alims-intl","name":"Alibaba Studio","alias":"alims-intl","category":"apikey","authType":"apikey","color":"#FF6A00","icon":"cloud","textIcon":"ALi"},
  {"id":"agentrouter","name":"Agent Router","alias":"agentrouter","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#7C5CFC","icon":"sway","textIcon":"SW","passthroughModels":true},
  {"id":"anthropic","name":"Anthropic","alias":"anthropic","category":"apikey","authType":"apikey","color":"#D97757","icon":"smart_toy","textIcon":"AN"},
  {"id":"antigravity","name":"Antigravity","alias":"ag","category":"oauth","authType":"oauth","color":"#F59E0B","icon":"rocket_launch"},
  {"id":"azure","name":"Azure OpenAI","alias":"azure","category":"apikey","authType":"apikey","color":"#0078D4","icon":"cloud","textIcon":"AZ"},
  {"id":"baidu","name":"Baidu Qianfan","alias":"qianfan","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#2932E1","icon":"search","textIcon":"BD"},
  {"id":"blackbox","name":"Blackbox AI","alias":"bb","category":"apikey","authType":"apikey","color":"#5B5FEF","icon":"smart_toy","textIcon":"BB"},
  {"id":"byteplus","name":"BytePlus ModelArk","alias":"bpm","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#2563EB","icon":"cloud","textIcon":"BP"},
  {"id":"cerebras","name":"Cerebras","alias":"cerebras","category":"apikey","authType":"apikey","color":"#FF4F00","icon":"memory","textIcon":"CB"},
  {"id":"chutes","name":"Chutes AI","alias":"ch","category":"apikey","authType":"apikey","color":"#ffffffff","icon":"water_drop","textIcon":"CH"},
  {"id":"claude","name":"Claude Code","alias":"cc","category":"oauth","authType":"oauth","color":"#D97757","icon":"smart_toy"},
  {"id":"cline","name":"Cline","alias":"cl","category":"oauth","authType":"oauth","color":"#5B9BD5","icon":"smart_toy","textIcon":"CL"},
  {"id":"clinepass","name":"ClinePass","alias":"clinepass","category":"oauth","authType":"oauth","authModes":["oauth","apikey"],"hasOAuth":true,"color":"#5B9BD5","icon":"vpn_key","textIcon":"CP"},
  {"id":"cloudflare-ai","name":"Cloudflare","alias":"cf","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#F38020","icon":"cloud","textIcon":"CF"},
  {"id":"codebuddy-cn","name":"CodeBuddy CN","alias":"cbcn","category":"oauth","authType":"device","authModes":["device","apikey","import"],"hasOAuth":true,"color":"#006EFF","icon":"smart_toy"},
  {"id":"codebuddy-intl","name":"CodeBuddy","alias":"cbai","category":"oauth","authType":"device","authModes":["device","apikey","import"],"hasOAuth":true,"color":"#006EFF","icon":"smart_toy"},
  {"id":"codex","name":"OpenAI Codex","alias":"cx","category":"oauth","authType":"oauth","color":"#3B82F6","icon":"code"},
  {"id":"commandcode","name":"Command Code","alias":"cmc","category":"apikey","authType":"apikey","color":"#000000","icon":"smart_toy","textIcon":"CC"},
  {"id":"cursor","name":"Cursor IDE","alias":"cu","category":"oauth","authType":"import","authModes":["import"],"color":"#00D4AA","icon":"edit_note"},
  {"id":"deepseek","name":"DeepSeek","alias":"ds","category":"apikey","authType":"apikey","color":"#4D6BFE","icon":"bolt","textIcon":"DS"},
  {"id":"featherless","name":"Featherless","alias":"fl","category":"apikey","authType":"apikey","color":"#111827","icon":"flutter_dash","textIcon":"FL"},
  {"id":"fireworks","name":"Fireworks AI","alias":"fireworks","category":"apikey","authType":"apikey","color":"#7B2EF2","icon":"local_fire_department","textIcon":"FW"},
  {"id":"gemini","name":"Gemini","alias":"gemini","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#4285F4","icon":"diamond","textIcon":"GE"},
  {"id":"gemini-cli","name":"Gemini CLI","alias":"gc","category":"oauth","authType":"oauth","color":"#4285F4","icon":"terminal"},
  {"id":"github","name":"GitHub Copilot","alias":"gh","category":"oauth","authType":"device","authModes":["device"],"color":"#333333","icon":"code"},
  {"id":"glm","name":"GLM Coding","alias":"glm","category":"apikey","authType":"apikey","color":"#2563EB","icon":"code","textIcon":"GL"},
  {"id":"glm-cn","name":"GLM (China)","alias":"glm-cn","category":"apikey","authType":"apikey","color":"#DC2626","icon":"code","textIcon":"GC"},
  {"id":"grok-cli","name":"Grok CLI (Grok Build)","alias":"gcli","category":"oauth","authType":"device","authModes":["device"],"hasOAuth":true,"color":"#1DA1F2","icon":"auto_awesome","textIcon":"GC"},
  {"id":"grok-web","name":"Grok Web (Subscription)","alias":"gw","category":"webCookie","authType":"cookie","color":"#1DA1F2","icon":"auto_awesome","textIcon":"GW"},
  {"id":"groq","name":"Groq","alias":"groq","category":"apikey","authType":"apikey","color":"#F55036","icon":"speed","textIcon":"GQ"},
  {"id":"kilo-gateway","name":"Kilo Gateway","alias":"kgw","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#8B5CF6","icon":"login","textIcon":"KG"},
  {"id":"kilocode","name":"Kilo Code","alias":"kc","category":"oauth","authType":"device","authModes":["device"],"color":"#FF6B35","icon":"code","textIcon":"KC"},
  {"id":"kimchi","name":"Kimchi","alias":"kimchi","category":"oauth","authType":"oauth","authModes":["oauth"],"hasOAuth":true,"color":"#FF521D","icon":"restaurant","textIcon":"KC"},
  {"id":"kimi","name":"Kimi","alias":"kimi","category":"oauth","authType":"device","authModes":["device","apikey"],"hasOAuth":true,"color":"#1E3A8A","icon":"psychology","textIcon":"KM"},
  {"id":"kiro","name":"Kiro AI","alias":"kr","category":"oauth","authType":"device","authModes":["device","apikey","import"],"color":"#FF6B35","icon":"psychology_alt"},
  {"id":"meta","name":"Meta AI","alias":"meta","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#0668E1","icon":"auto_awesome","textIcon":"MA","passthroughModels":true},
  {"id":"minimax","name":"Minimax Coding","alias":"minimax","category":"apikey","authType":"apikey","color":"#7C3AED","icon":"memory","textIcon":"MM"},
  {"id":"minimax-cn","name":"Minimax (China)","alias":"minimax-cn","category":"apikey","authType":"apikey","color":"#DC2626","icon":"memory","textIcon":"MC"},
  {"id":"mistral","name":"Mistral","alias":"mistral","category":"apikey","authType":"apikey","color":"#FF7000","icon":"air","textIcon":"MI"},
  {"id":"morph","name":"Morph","alias":"morph","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#14B8A6","icon":"change_history","textIcon":"MP"},
  {"id":"nebius","name":"Nebius AI","alias":"nebius","category":"apikey","authType":"apikey","color":"#6C5CE7","icon":"cloud","textIcon":"NB"},
  {"id":"nvidia","name":"NVIDIA NIM","alias":"nvidia","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#76B900","icon":"developer_board","textIcon":"NV"},
  {"id":"ollama","name":"Ollama Cloud","alias":"ollama","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#ffffffff","icon":"cloud","textIcon":"OL"},
  {"id":"ollama-local","name":"Ollama Local","alias":"ollama-local","category":"apikey","authType":"apikey","color":"#ffffffff","icon":"cloud","textIcon":"OL"},
  {"id":"openai","name":"OpenAI","alias":"openai","category":"apikey","authType":"apikey","color":"#10A37F","icon":"auto_awesome","textIcon":"OA"},
  {"id":"opencode","name":"OpenCode Free","alias":"oc","category":"none","authType":"none","noAuth":true,"color":"#E87040","icon":"terminal","textIcon":"OC"},
  {"id":"opencode-go","name":"OpenCode Go","alias":"ocg","category":"apikey","authType":"apikey","color":"#E87040","icon":"terminal","textIcon":"OC"},
  {"id":"openrouter","name":"OpenRouter","alias":"openrouter","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#F97316","icon":"router","textIcon":"OR"},
  {"id":"perplexity","name":"Perplexity AI","alias":"pplx","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#20808D","icon":"search","textIcon":"PP","passthroughModels":true},
  {"id":"poolside","name":"Poolside","alias":"ps","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#0EA5E9","icon":"water_drop","textIcon":"PS"},
  {"id":"qoder","name":"Qoder","alias":"qd","category":"oauth","authType":"device","authModes":["device","apikey"],"hasOAuth":true,"color":"#EC4899","icon":"water_drop"},
  {"id":"sumopod","name":"SumoPod","alias":"sumopod","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#F4F4F5","icon":"sumopod","textIcon":"SP","passthroughModels":true},
  {"id":"tencent","name":"Tencent Hunyuan","alias":"hunyuan","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#0052D9","icon":"cloud","textIcon":"HY"},
  {"id":"together","name":"Together AI","alias":"together","category":"apikey","authType":"apikey","color":"#0F6FFF","icon":"group_work","textIcon":"TG"},
  {"id":"trae","name":"Trae","alias":"tr","category":"oauth","authType":"oauth","authModes":["oauth"],"hasOAuth":true,"color":"#FF6A00","icon":"bolt","textIcon":"TR"},
  {"id":"venice","name":"Venice AI","alias":"venice","category":"apikey","authType":"apikey","color":"#DC2626","icon":"shield","textIcon":"VE"},
  {"id":"vercel-ai-gateway","name":"Vercel AI Gateway","alias":"vercel","category":"apikey","authType":"apikey","color":"#111827","icon":"deployed_code","textIcon":"VG"},
  {"id":"vertex","name":"Vertex AI","alias":"vx","category":"apikey","authType":"apikey","authModes":["apikey"],"color":"#4285F4","icon":"cloud","textIcon":"VX"},
  {"id":"vertex-partner","name":"Vertex Partner","alias":"vxp","category":"apikey","authType":"apikey","color":"#34A853","icon":"cloud","textIcon":"VP"},
  {"id":"windsurf","name":"Windsurf","alias":"ws","category":"oauth","authType":"oauth","authModes":["oauth","apikey"],"hasOAuth":true,"color":"#14B8A6","icon":"surfing"},
  {"id":"xai","name":"xAI (Grok)","alias":"xai","category":"oauth","authType":"oauth","authModes":["oauth","apikey"],"hasOAuth":true,"color":"#1DA1F2","icon":"auto_awesome","textIcon":"XA"},
  {"id":"xiaomi-mimo","name":"Xiaomi MiMo","alias":"mimo","category":"apikey","authType":"apikey","color":"#FF6900","icon":"smart_toy","textIcon":"XM"},
  {"id":"xiaomi-tokenplan","name":"Xiaomi MiMo (Token Plan)","alias":"xmtp","category":"apikey","authType":"apikey","color":"#FF6700","icon":"smart_toy","textIcon":"XT"}
];
