export default {
  id: "codebuddy-intl",
  alias: "cbai",
  uiAlias: "cbai",
  hidden: false,
  priority: 90,
  display: {
    name: "CodeBuddy",
    icon: "smart_toy",
    color: "#006EFF",
    website: "https://www.codebuddy.ai",
    notice: {
      signupUrl: "https://www.codebuddy.ai",
    },
  },
  category: "oauth",
  authModes: ["device", "apikey", "import"],
  hasOAuth: true,
  passthroughModels: true,
  transport: {

    baseUrl: "https://www.codebuddy.ai/v2/chat/completions",
    forceStream: true,

    thinkingFormat: "openai",
    headers: {
      "User-Agent": "IDE/2.108.1 CodeBuddy/2.108.1",
      "X-Product": "SaaS",
      "X-IDE-Type": "IDE",
      "X-IDE-Name": "IDE",
      "x-requested-with": "XMLHttpRequest",
      "x-codebuddy-request": "1",
    },
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
    },

    usage: {
      url: "https://www.codebuddy.ai/billing/meter/get-user-resource",
    },
  },

  models: [
    { id: "auto", name: "Auto" },
    { id: "balanced-model", name: "Balanced" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "claude-opus-4.7-1m", name: "Claude Opus 4.7 1M" },
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "deep-model", name: "Deep" },
    { id: "deepseek-v3-0324", name: "DeepSeek V3 0324" },
    { id: "deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash" },
    { id: "default-model", name: "Default" },
    { id: "fast-model", name: "Fast" },
    { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro" },
    { id: "glm-5.1", name: "GLM-5.1" },
    { id: "glm-5.2", name: "GLM-5.2" },
    { id: "glm-5.3", name: "GLM-5.3" },
    { id: "glm-5v-turbo", name: "GLM-5V Turbo" },
    { id: "gpt-5.3-codex", name: "GPT-5.3 Codex" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "hy3", name: "HY3" },
    { id: "hy4-preview", name: "HY4 Preview" },
    { id: "hy4-preview-x", name: "HY4 Preview X" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.7", name: "Kimi K2.7" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "minimax-m3", name: "MiniMax M3" },
    { id: "primary-model", name: "Primary" },
  ],
  oauth: {
    baseUrl: "https://www.codebuddy.ai",
    stateUrl: "https://www.codebuddy.ai/v2/plugin/auth/state",
    tokenUrl: "https://www.codebuddy.ai/v2/plugin/auth/token",
    refreshUrl: "https://www.codebuddy.ai/v2/plugin/auth/token/refresh",
    userAgent: "IDE/2.63.2 CodeBuddy/2.63.2",
    platform: "ide",
    pollInterval: 5000,
  },
  features: {
    usage: true,
    usageApikey: true,
  },
};
