export default {
  id: "codebuddy-cn",

  alias: "cbcn",
  uiAlias: "cbcn",
  hidden: false,
  priority: 90,
  display: {
    name: "CodeBuddy CN",
    icon: "smart_toy",
    color: "#006EFF",
    website: "https://copilot.tencent.com",
    notice: {
      signupUrl: "https://copilot.tencent.com",
    },
  },
  category: "oauth",
  authModes: ["device", "import"],
  hasOAuth: true,
  passthroughModels: true,
  transport: {
    baseUrl: "https://copilot.tencent.com/v2/chat/completions",
    forceStream: true,

    thinkingFormat: "openai",
    headers: {
      "User-Agent": "CLI/2.108.1 CodeBuddy/2.108.1",
      "X-Product": "SaaS",
      "X-IDE-Type": "CLI",
      "X-IDE-Name": "CLI",
      "x-requested-with": "XMLHttpRequest",
      "x-codebuddy-request": "1",
    },
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
    },

    usage: {
      url: "https://copilot.tencent.com/v2/billing/meter/get-user-resource",
    },
  },
  models: [
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "kimi-k3-1", name: "Kimi K3-1" },
    { id: "kimi-k2.8-preview", name: "Kimi K2.8 Preview" },
    { id: "kimi-k2.7", name: "Kimi K2.7" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "glm-5.3", name: "GLM-5.3" },
    { id: "glm-5.3-flash", name: "GLM-5.3 Flash" },
    { id: "glm-5.3-flashx", name: "GLM-5.3 FlashX" },
    { id: "glm-5.2", name: "GLM-5.2" },
    { id: "glm-5.1", name: "GLM-5.1" },
    { id: "glm-5v-turbo", name: "GLM-5V Turbo" },
    { id: "glm-5.0-turbo", name: "GLM-5.0 Turbo" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash" },
    { id: "deepseek-v3-2-volc", name: "DeepSeek V3.2 Volc" },
    { id: "deepseek-v3-1-lkeap", name: "DeepSeek V3.1 LKEAP" },
    { id: "deepseek-v3-0324-lkeap", name: "DeepSeek V3 0324 LKEAP" },
    { id: "deepseek-r1-0528-lkeap", name: "DeepSeek R1 0528 LKEAP" },
    { id: "deepseek-v3-0324", name: "DeepSeek V3 0324" },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
    { id: "minimax-m3", name: "MiniMax M3" },
    { id: "hy3", name: "HY3" },
    { id: "hy4-preview", name: "HY4 Preview" },
    { id: "hy4-preview-f", name: "HY4 Preview F" },
    { id: "hunyuan-2.0-thinking", name: "Hunyuan 2.0 Thinking" },
    { id: "hunyuan-2.0-instruct", name: "Hunyuan 2.0 Instruct" },
    { id: "hunyuan-chat", name: "Hunyuan Chat" },
    { id: "codewise-rewrite", name: "Codewise Rewrite" },
    { id: "codewise-nes-a4-027-aide", name: "Codewise NES A4 027 Aide" },
    { id: "codewise-jump", name: "Codewise Jump" },
  ],
  oauth: {
    baseUrl: "https://copilot.tencent.com",
    stateUrl: "https://copilot.tencent.com/v2/plugin/auth/state",
    tokenUrl: "https://copilot.tencent.com/v2/plugin/auth/token",
    refreshUrl: "https://copilot.tencent.com/v2/plugin/auth/token/refresh",
    userAgent: "CLI/2.63.2 CodeBuddy/2.63.2",
    platform: "CLI",
    pollInterval: 5000,
  },
  features: {
    usage: true,
    usageApikey: true,
  },
};
