export default {
  id: "sumopod",
  priority: 125,
  alias: "sumopod",
  display: {
    name: "SumoPod",
    icon: "sumopod",
    color: "#F4F4F5",
    textIcon: "SP",
    website: "https://sumopod.com",
    notice: {
      text: "OpenAI-compatible API with configurable budget limits.",
      apiKeyUrl: "https://sumopod.com/dashboard/ai/keys",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://ai.sumopod.com/v1/chat/completions",
    validateUrl: "https://ai.sumopod.com/v1/models",
    format: "openai",
    openaiCompatible: true,
  },
  models: [
    { id: "claude-haiku-4-5", name: "Claude Haiku 4.5" },
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision Exp" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "gemini/gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "gemini/gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite" },
    { id: "gemini/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "gemini/gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "gemini/gemini-3.5-flash-lite", name: "Gemini 3.5 Flash Lite" },
    { id: "gemini/gemini-embedding-001", name: "Gemini Embedding 001" },
    { id: "glm-5", name: "GLM 5" },
    { id: "glm-5-turbo", name: "GLM 5 Turbo" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "glm-5v-turbo", name: "GLM 5V Turbo" },
    { id: "gpt-4.1", name: "GPT-4.1" },
    { id: "gpt-4.1-mini", name: "GPT-4.1 Mini" },
    { id: "gpt-4.1-nano", name: "GPT-4.1 Nano" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "gpt-5", name: "GPT-5" },
    { id: "gpt-5-mini", name: "GPT-5 Mini" },
    { id: "gpt-5-nano", name: "GPT-5 Nano" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini" },
    { id: "gpt-5.4-nano", name: "GPT-5.4 Nano" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "hy3", name: "HY3" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.7", name: "Kimi K2.7" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "MiniMax-M2.7-highspeed", name: "MiniMax M2.7 Highspeed" },
    { id: "MiniMax-M3", name: "MiniMax M3" },
    { id: "qwen3.6-flash", name: "Qwen 3.6 Flash" },
    { id: "qwen3.6-plus", name: "Qwen 3.6 Plus" },
    { id: "qwen3.7-flash-2026-07-15", name: "Qwen 3.7 Flash" },
    { id: "qwen3.7-max", name: "Qwen 3.7 Max" },
    { id: "qwen3.7-plus", name: "Qwen 3.7 Plus" },
    { id: "qwen3.8-flash", name: "Qwen 3.8 Flash" },
    { id: "qwen3.8-max", name: "Qwen 3.8 Max" },
    { id: "seed-2-0-code", name: "Seed 2.0 Code" },
    { id: "seed-2-0-lite", name: "Seed 2.0 Lite" },
    { id: "seed-2-0-mini", name: "Seed 2.0 Mini" },
    { id: "seed-2-0-pro", name: "Seed 2.0 Pro" },
    { id: "text-embedding-3-large", name: "Text Embedding 3 Large" },
    { id: "text-embedding-3-small", name: "Text Embedding 3 Small" },
  ],
  modelsFetcher: {
    url: "https://ai.sumopod.com/v1/models",
    type: "openai",
  },
  passthroughModels: true,
};
